### PR TITLE
Add flag to control SSL verify mode.

### PR DESCRIPTION
**Pull request by jsiembida**

### CODE REVIEW

**Comment by pgjones** [comment]
I think that there should just be the basic options in this method, it is meant to only be used for development. Is using hypercorn directly problematic in this case?

**Comment by jsiembida** [comment]
There already are cipher specific options in Quart run. The API looks customisable but not quite. Perhaps it should be pushed into either direction as it is unclear how to use it with SSL.

**Comment by pgjones** [comment]
Good point, I think then I'll remove the cipher option and improve the docstring.

**Comment by jsiembida** [comment]
Sure, documentation dedicated to the intended SSL usage pattern would definitely go a long way.

**Comment by pgjones** [comment]
See a4337739f024a3efce14b626ff1a437716e57a6e for the new signature for the run method. I have added this and addition settings to the latest Hypercorn release though.

**Pull request closed without merging**
